import { Download } from 'lucide-react'

import { reportService } from '@/services'
import { useAsync } from '@/lib/useAsync'
import { formatDate } from '@/lib/format'
import { useToast } from '@/lib/toast'
import { ProgressChart } from '@/charts/ProgressChart'
import { Button } from '@/components/ui/Button'
import { Drawer } from '@/components/ui/Modal'
import { SkeletonText } from '@/components/ui/Skeleton'
import { ErrorState } from '@/components/ui/States'

/**
 * Reads a stored report.
 *
 * The list endpoint omits `sections` so the table stays light, so the full
 * body is fetched here when a report is actually opened.
 */
export function ReportView({ report, onClose }) {
  const toast = useToast()
  const { data, error, loading, reload } = useAsync(
    () => (report ? reportService.get(report.id) : Promise.resolve(null)),
    [report?.id],
  )

  const full = data?.sections ? data : report?.sections ? report : null

  const exportCsv = () => {
    if (!full) return
    const lines = [
      `${full.title} — ${full.project_name}`,
      `Generated ${formatDate(full.created_at)} by ${full.generated_by || 'unknown'}`,
      '',
    ]
    full.sections.forEach((section) => {
      lines.push(section.heading)
      if (section.kind === 'metrics') {
        section.items.forEach((item) => lines.push(`${item.label},${item.value}`))
      } else if (section.kind === 'table') {
        lines.push(section.columns.join(','))
        section.rows.forEach((row) =>
          lines.push(row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(',')),
        )
      } else if (section.kind === 'list') {
        section.items.forEach((item) => lines.push(`"${String(item).replace(/"/g, '""')}"`))
      }
      lines.push('')
    })
    const blob = new Blob([lines.join('\n')], { type: 'text/csv;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const anchor = document.createElement('a')
    anchor.href = url
    anchor.download = `${full.report_type}-${new Date().toISOString().slice(0, 10)}.csv`
    anchor.click()
    URL.revokeObjectURL(url)
    toast.success('Report exported', 'Saved as CSV')
  }

  return (
    <Drawer
      open={Boolean(report)}
      onClose={onClose}
      title={report?.title || 'Report'}
      description={
        report
          ? `${report.project_name} · ${report.period_days} days · generated by ${report.generated_by || 'unknown'}`
          : ''
      }
      width="max-w-3xl"
      footer={
        full && (
          <Button variant="secondary" onClick={exportCsv}>
            <Download size={14} />
            Download CSV
          </Button>
        )
      }
    >
      {loading && !full ? (
        <SkeletonText lines={10} />
      ) : error && !full ? (
        <ErrorState
          compact
          title="Unable to load this report"
          description={error.message}
          onRetry={reload}
        />
      ) : !full ? null : (
        <div className="space-y-6">
          {full.sections.map((section, index) => (
            <section key={`${section.heading}-${index}`}>
              <h3 className="panel-title mb-3.5">{section.heading}</h3>

              {section.kind === 'metrics' && (
                <dl className="grid grid-cols-2 gap-4 sm:grid-cols-3">
                  {section.items.map((item) => (
                    <div key={item.label} className="rounded-panel border border-line bg-raised p-4">
                      <dd className="font-display text-h4 font-semibold tabular text-ink">
                        {item.value}
                      </dd>
                      <dt className="mt-0.5 text-tiny text-muted">{item.label}</dt>
                    </div>
                  ))}
                </dl>
              )}

              {section.kind === 'table' && (
                <div className="overflow-x-auto rounded-panel border border-line">
                  <table className="w-full border-collapse text-base" style={{ minWidth: '34rem' }}>
                    <thead>
                      <tr className="border-b border-line bg-raised/60">
                        {section.columns.map((column) => (
                          <th
                            key={column}
                            scope="col"
                            className="px-4 py-2.5 text-left text-tiny font-medium text-muted"
                          >
                            {column}
                          </th>
                        ))}
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-line">
                      {section.rows.length === 0 ? (
                        <tr>
                          <td
                            colSpan={section.columns.length}
                            className="px-4 py-6 text-center text-base text-muted"
                          >
                            Nothing recorded in this period.
                          </td>
                        </tr>
                      ) : (
                        section.rows.map((row, rowIndex) => (
                          <tr key={rowIndex} className="transition-colors duration-150 hover:bg-raised">
                            {row.map((cell, cellIndex) => (
                              <td
                                key={cellIndex}
                                className="px-4 py-3 align-middle text-muted first:font-medium first:text-ink"
                              >
                                {cell}
                              </td>
                            ))}
                          </tr>
                        ))
                      )}
                    </tbody>
                  </table>
                </div>
              )}

              {section.kind === 'list' && (
                <ul className="space-y-2">
                  {section.items.map((item, itemIndex) => (
                    <li
                      key={itemIndex}
                      className="rounded-control border border-line bg-raised px-3.5 py-2.5 text-base leading-relaxed text-muted"
                    >
                      {item}
                    </li>
                  ))}
                </ul>
              )}

              {section.kind === 'chart' && section.chart?.data?.length > 0 && (
                <ProgressChart data={section.chart.data} title="Planned against actual" height={260} />
              )}
            </section>
          ))}
        </div>
      )}
    </Drawer>
  )
}
