import { useMemo, useState } from 'react'
import { Download, Eye, FileBarChart, Plus, Trash2 } from 'lucide-react'

import { projectService, reportService } from '@/services'
import { useAsync, useDebounced } from '@/lib/useAsync'
import { formatDate, relativeTime, titleise } from '@/lib/format'
import { useToast } from '@/lib/toast'
import { useEnter } from '@/animations/useMotion'
import { PageHeader } from '@/layouts/PageHeader'
import { Button } from '@/components/ui/Button'
import { ConfirmDialog, Modal } from '@/components/ui/Modal'
import { Field, FieldRow, Select } from '@/components/ui/Form'
import { AdminTable, AdminToolbar } from '@/features/admin/AdminTable'
import { RowMenu } from '@/features/admin/RowMenu'
import { ReportView } from '@/features/admin/ReportView'

const PERIODS = [
  { value: '7', label: 'Last 7 days' },
  { value: '30', label: 'Last 30 days' },
  { value: '90', label: 'Last 90 days' },
]

export default function AdminReports() {
  const toast = useToast()
  const [query, setQuery] = useState('')
  const debounced = useDebounced(query, 250)
  const [type, setType] = useState('')

  const { data, error, loading, reload } = useAsync(() => reportService.list(), [])
  const { data: types } = useAsync(() => reportService.types(), [])
  const { data: projects } = useAsync(() => projectService.list(), [])
  const scope = useEnter([loading, Boolean(data)])

  const [generateOpen, setGenerateOpen] = useState(false)
  const [viewing, setViewing] = useState(null)
  const [confirm, setConfirm] = useState(null)
  const [busy, setBusy] = useState(false)

  const rows = useMemo(() => {
    let list = data || []
    if (type) list = list.filter((row) => row.report_type === type)
    if (debounced) {
      const needle = debounced.toLowerCase()
      list = list.filter(
        (row) =>
          row.title?.toLowerCase().includes(needle) ||
          row.project_name?.toLowerCase().includes(needle) ||
          row.generated_by?.toLowerCase().includes(needle),
      )
    }
    return list
  }, [data, type, debounced])

  const remove = async (report) => {
    setBusy(true)
    try {
      await reportService.remove(report.id)
      toast.success('Report deleted.')
      setConfirm(null)
      reload()
    } catch (err) {
      toast.error(err.status === 403 ? 'Your role cannot delete reports.' : err.message)
    } finally {
      setBusy(false)
    }
  }

  const columns = useMemo(
    () => [
      {
        key: 'title',
        header: 'Report',
        value: (row) => row.title,
        render: (row) => (
          <div className="min-w-0">
            <span className="block truncate font-medium text-ink">{row.title}</span>
            <span className="block truncate text-tiny text-subtle">{row.project_name}</span>
          </div>
        ),
      },
      {
        key: 'report_type',
        header: 'Type',
        value: (row) => row.report_type,
        render: (row) => (
          <span className="whitespace-nowrap rounded-pill border border-line bg-raised px-2 py-0.5 text-micro text-muted">
            {titleise(row.report_type)}
          </span>
        ),
      },
      {
        key: 'period_days',
        header: 'Period',
        align: 'right',
        sortValue: (row) => row.period_days || 0,
        render: (row) => <span className="whitespace-nowrap text-tiny text-muted">{row.period_days} days</span>,
      },
      {
        key: 'generated_by',
        header: 'Generated by',
        value: (row) => row.generated_by,
        render: (row) => <span className="truncate text-muted">{row.generated_by || '—'}</span>,
      },
      {
        key: 'created_at',
        header: 'Created',
        align: 'right',
        sortValue: (row) => row.created_at || '',
        render: (row) => (
          <div>
            <span className="block whitespace-nowrap text-tiny text-ink">
              {relativeTime(row.created_at)}
            </span>
            <span className="block whitespace-nowrap text-micro text-subtle">
              {formatDate(row.created_at)}
            </span>
          </div>
        ),
      },
      {
        key: 'actions',
        header: '',
        sortable: false,
        width: '3rem',
        align: 'right',
        render: (row) => (
          <RowMenu
            label={`Actions for ${row.title}`}
            items={[
              { label: 'View report', icon: Eye, onSelect: () => setViewing(row) },
              { label: 'Delete report', icon: Trash2, destructive: true, onSelect: () => setConfirm(row) },
            ]}
          />
        ),
      },
    ],
    [],
  )

  return (
    <div ref={scope}>
      <PageHeader
        eyebrow="Admin"
        title="Reports"
        description="Every report generated on the platform, by anyone, with the period it covers."
        actions={
          <Button variant="primary" onClick={() => setGenerateOpen(true)}>
            <Plus size={14} />
            Generate report
          </Button>
        }
      />

      <div data-enter>
        <AdminToolbar
          query={query}
          onQuery={setQuery}
          placeholder="Search reports…"
          filters={[
            {
              key: 'type',
              label: 'All types',
              value: type,
              onChange: setType,
              options: (types || []).map((item) => ({ value: item.value, label: item.label })),
            },
          ]}
        />
      </div>

      <div data-enter>
        <AdminTable
          loading={loading}
          error={error}
          onRetry={reload}
          rows={rows}
          columns={columns}
          filtered={Boolean(debounced || type)}
          minWidth="62rem"
          emptyIcon={FileBarChart}
          emptyTitle="No reports yet"
          emptyDescription="Generate the first report to capture where the portfolio stands today."
          filteredTitle="No reports found"
          errorTitle="Unable to load reports"
          action={
            <Button variant="primary" onClick={() => setGenerateOpen(true)}>
              <Plus size={14} />
              Generate report
            </Button>
          }
        />
      </div>

      <GenerateReportModal
        open={generateOpen}
        onClose={() => setGenerateOpen(false)}
        onGenerated={(report) => {
          reload()
          setViewing(report)
        }}
        types={types || []}
        projects={projects || []}
      />

      <ReportView report={viewing} onClose={() => setViewing(null)} />

      <ConfirmDialog
        open={Boolean(confirm)}
        onClose={() => setConfirm(null)}
        title={confirm ? `Delete "${confirm.title}"?` : ''}
        description="This removes the stored report. The underlying project data is untouched, so the same report can be generated again."
        confirmLabel="Delete report"
        loading={busy}
        onConfirm={() => confirm && remove(confirm)}
      />
    </div>
  )
}

function GenerateReportModal({ open, onClose, onGenerated, types, projects }) {
  const toast = useToast()
  const [reportType, setReportType] = useState('weekly_project')
  const [projectId, setProjectId] = useState('')
  const [period, setPeriod] = useState('30')
  const [busy, setBusy] = useState(false)

  const submit = async () => {
    setBusy(true)
    try {
      const report = await reportService.generate({
        report_type: reportType,
        project_id: projectId || null,
        period_days: Number(period),
      })
      toast.success('Report generated.', report.title)
      onGenerated?.(report)
      onClose()
    } catch (error) {
      toast.error(error.status === 403 ? 'Your role cannot generate reports.' : error.message)
    } finally {
      setBusy(false)
    }
  }

  return (
    <Modal
      open={open}
      onClose={onClose}
      title="Generate report"
      description="Built from live project data at the moment you generate it."
      size="md"
      footer={
        <>
          <Button variant="secondary" onClick={onClose} disabled={busy}>
            Cancel
          </Button>
          <Button variant="primary" onClick={submit} loading={busy}>
            Generate
          </Button>
        </>
      }
    >
      <div className="space-y-4">
        <Field label="Report type" required>
          <Select value={reportType} onChange={(event) => setReportType(event.target.value)}>
            {types.map((item) => (
              <option key={item.value} value={item.value}>
                {item.label}
              </option>
            ))}
          </Select>
        </Field>
        <FieldRow>
          <Field label="Project" hint="Leave as all projects for a portfolio report.">
            <Select value={projectId} onChange={(event) => setProjectId(event.target.value)}>
              <option value="">All projects</option>
              {projects.map((project) => (
                <option key={project.id} value={project.id}>
                  {project.name}
                </option>
              ))}
            </Select>
          </Field>
          <Field label="Period">
            <Select value={period} onChange={(event) => setPeriod(event.target.value)}>
              {PERIODS.map((item) => (
                <option key={item.value} value={item.value}>
                  {item.label}
                </option>
              ))}
            </Select>
          </Field>
        </FieldRow>
      </div>
    </Modal>
  )
}
